[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "script-src localhost:1313 cube-italia.com netlify.app"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
